development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: MapNotes_dev
  pool: 5
  username: root
  password: 123456

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: MapNotes_test
  pool: 5
  username: root
  password: 123456


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: MapNotes_pro
  pool: 5
  username: root
  password: 123456
